Repository cms-data/L1Trigger-Phase2L1ParticleFlow, pull requests merged in 2020-07, with the labels that each got.

#1 Data for package Phase2 L1 Particle Flow
  emcorr_barrel.root
  emcorr_hgc.root
  emcorr_hgc_106X.root
  emcorr_hgc_110X.root
  hadcorr_HGCal3D_TC.root
  hadcorr_HGCal3D_TC_106X.root
  hadcorr_HGCal3D_TC_110X.root
  hadcorr_barrel.root
  hadcorr_barrel_106X.root
  hadcorr_barrel_110X.root
  hfcorr.root
  hfcorr_106X.root
  hfcorr_110X.root
  hgcal_egID/Photon_Pion_vs_Neutrino_BDTweights.xml.gz
  hgcal_egID/Photon_vs_Pion_BDTweights.xml.gz
  jecs/jecs.PU200_106X.root
  jecs/jecs.PU200_110X.root
Labels: comparison-notrun, externals-pending, l1-approved, orp-approved, pending-signatures, requires-external, tests-started, upgrade-pending

#2 PF/Puppi Tau from L1TDR.
  tau_3layer.pb
  tau_3layer_puppi.pb
Labels: comparison-pending, externals-pending, l1-approved, orp-approved, pending-signatures, tests-started, upgrade-pending

#3 Rederived L1PF calibration files based on HGCal TPs from CMSSW 11_1_0_patch2
  hadcorr_HGCal3D_TC_110X.root
  hfcorr_110X.root
  jecs/jecs.PU200_110X.root
Labels: comparison-pending, externals-pending, l1-pending, orp-approved, pending-signatures, tests-pending, upgrade-pending
